const antipodes = {
  "Effective Accelerationism": "Degrowth",
  "Crypto-Anarchism": "Eco-Fascism",
  "Decentralized Accelerationism": "Theocracy",
  "Fully Automated Luxury Communism": "Kaczynskism",
  "Eco-Fascism": "Crypto-Anarchism",
  "Anarcho-Primitivism": "Neoreaction",
  "Degrowth": "Abundance",
  "Kaczynskism": "Fully Automated Luxury Communism",
  "Abundance": "Degrowth",
  "u/acc": "Degrowth",
  "Social Democracy": "Traditionalist Conservatism",
  "MAGA": "Mutualism",
  "Progressivism": "Libertarianism",
  "Anarcho-Capitalism": "Eco-Fascism",
  "Libertarianism": "Maoism",
  "Democratic Socialism": "Traditionalist Conservatism",
  "Neoliberalism": "Degrowth",
  "Mutualism": "Monarchism",
  "Market Socialism": "Monarchism",
  "Solarpunk": "Theocracy",
  "Green Capitalism": "Progressivism",
  "Georgism": "Progressivism",
  "Marxist-Leninism": "Kaczynskism",
  "Maoism": "Anarcho-Capitalism",
  "Fascism": "Traditionalist Conservatism",
  "Anarcho-Communism": "Monarchism",
  "Traditionalist Conservatism": "Social Democracy",
  "Monarchism": "Market Socialism",
  "Neoreaction": "Anarcho-Primitivism",
  "Theocracy": "Solarpunk"
};
